# Juan Ramón López Rocha #

### 26 de agosto ###

### 1. Tomaremos el archivo "datos CT" y calcularemos: ###

* Utilidad
* Promedio de los gastos en los meses que la utilidad fue negativa
* Ingresos totales del año

In [2]:
import pandas as pd

datos = pd.read_excel("datosCT.xlsx")
datos

Unnamed: 0  Ingreso  Gasto
0        Enero     1340   1880
1      Febrero     2590   3130
2        Marzo     3570   2140
3        Abril     4450   3370
4         Mayo     1330   2990
5        Junio     1610   1970
6        Julio     1500   2230
7       Agosto     2270   1240
8   Septiembre     1910   1470
9      Octubre     2120   2280
10   Noviembre     3950   1870
11   Diciembre     1380   3140

In [4]:
datos["Utilidad"] = datos["Ingreso"] - datos["Gasto"]
datos

Unnamed: 0  Ingreso  Gasto  Utilidad
0        Enero     1340   1880      -540
1      Febrero     2590   3130      -540
2        Marzo     3570   2140      1430
3        Abril     4450   3370      1080
4         Mayo     1330   2990     -1660
5        Junio     1610   1970      -360
6        Julio     1500   2230      -730
7       Agosto     2270   1240      1030
8   Septiembre     1910   1470       440
9      Octubre     2120   2280      -160
10   Noviembre     3950   1870      2080
11   Diciembre     1380   3140     -1760

In [48]:
gastos = datos[datos["Utilidad"] < 0]
prom_gastos = gastos["Gasto"].mean()
prom_gastos

2517.1428571428573

In [50]:
ingresos = datos["Ingreso"].sum()
ingresos

28020

### 2. Vamos a crear estructuras usando numpy ###

In [59]:
import numpy as np

A = np.array ([
    [1,2],
    [3,4]
])

A

array([[1, 2],
       [3, 4]])

In [60]:
b = np.array ([
    [2],
    [4]
])

b

array([[2],
       [4]])

In [61]:
#Encontraremos el resultado: Ab
A @ b

array([[10],
       [22]])